### ISSUE TITLE
Composer should not raise warnings.

### ISSUE THREAD

**Issue by Tjoosten** [ircmaxell/Tuli#3]
MacBook-Pro-van-Tim:iRail-work tim$ sudo composer require ircmaxell/tuli dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ircmaxell/tuli could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Installation failed, reverting ./composer.json to its original content.
MacBook-Pro-van-Tim:iRail-work tim$

**Comment by ircmaxell** [comment]
This should be fixed. can you try again?

**Comment by Tjoosten** [comment]
Still the same error.

**Comment by ghost** [comment]
In your composer.json, you've set:
"name": "ircmaxell/php-tuli", just tuli would be okay.

Anyway, you should submit your app on https://packagist.org/ so that people can install it through composer :)

**Comment by ircmaxell** [comment]
Renamed the package (I was originally going to name it php-tuli). 

As far as packagist, it's still a bit early for that. I want to get it even remotely stable prior to that sort of publication...

**Comment by ircmaxell** [comment]
Nevermind, submitted to packagist.
